"""Interactive HTML graph builder.

Assembles wiki/knowledge-graph.html from:
  - wiki/graph-data.json (generated by graph_analysis.py)
  - templates/graph-styles/wash/ (header.html, footer.html, graph-wash.js)
  - deps/ (d3.min.js only — rough/marked/purify removed)

The adapted data preserves original edge types (supports/contradicts/etc)
and fills node content from vault pages.
"""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path

from .shared import parse_frontmatter, section_excerpt
from .graph_analysis import build_graph_data


def _read_node_content(vault: Path, ref: str) -> str:
    """Read a wiki page and extract type-appropriate content for the drawer."""
    parts = ref.split("/", 1)
    if len(parts) < 2:
        return ""
    page_path = vault / "wiki" / parts[0] / f"{parts[1]}.md"
    if not page_path.exists():
        return ""
    text = page_path.read_text(encoding="utf-8")
    meta, body = parse_frontmatter(text)
    page_type = meta.get("type", parts[0])

    if page_type == "source":
        core = section_excerpt(body, "核心摘要") or ""
        relation = section_excerpt(body, "与现有知识库的关系") or ""
        parts_list = []
        if core:
            parts_list.append(f"核心摘要：{core[:300]}")
        if relation:
            parts_list.append(f"知识库关系：{relation[:200]}")
        return "\n".join(parts_list)
    elif page_type == "brief":
        conclusion = section_excerpt(body, "一句话结论") or ""
        key_points = section_excerpt(body, "核心要点") or ""
        parts_list = []
        if conclusion:
            parts_list.append(conclusion[:300])
        if key_points:
            parts_list.append(f"要点：{key_points[:300]}")
        return "\n".join(parts_list)
    elif page_type == "stance":
        judgement = section_excerpt(body, "核心判断") or ""
        support = section_excerpt(body, "支持证据") or ""
        oppose = section_excerpt(body, "反对证据（steel-man）") or ""
        parts_list = []
        if judgement:
            parts_list.append(f"核心判断：{judgement[:300]}")
        if support:
            parts_list.append(f"支持：{support[:200]}")
        if oppose:
            parts_list.append(f"反驳：{oppose[:200]}")
        return "\n".join(parts_list)
    elif page_type == "question":
        q_text = section_excerpt(body, "问题") or ""
        answer = section_excerpt(body, "部分回答") or ""
        parts_list = []
        if q_text:
            parts_list.append(f"问题：{q_text[:300]}")
        if answer:
            parts_list.append(f"部分回答：{answer[:200]}")
        return "\n".join(parts_list)
    elif page_type == "synthesis":
        conclusion = section_excerpt(body, "当前结论") or ""
        sources = section_excerpt(body, "近期来源") or ""
        parts_list = []
        if conclusion:
            parts_list.append(conclusion[:300])
        if sources:
            parts_list.append(f"近期来源：{sources[:200]}")
        return "\n".join(parts_list)
    elif page_type in ("concept", "entity"):
        definition = section_excerpt(body, "定义") or body[:300]
        return definition[:400]
    elif page_type == "domain":
        return body[:400]
    else:
        return body[:300]


def _compute_learning_path(skeleton_nodes: list, edges: list) -> list:
    """Order skeleton nodes into a learning path by dependency layer.

    Layer 0: domains (foundational)
    Layer 1: concepts/entities with no incoming skeleton edges
    Layer 2: concepts/entities that depend on layer 0-1
    Layer 3: syntheses/comparisons
    Layer 4: stances/questions
    """
    SKELETON_TYPES = {"concept", "entity", "domain", "synthesis", "comparison"}
    by_id = {n["id"]: n for n in skeleton_nodes}
    incoming = {n["id"]: 0 for n in skeleton_nodes}
    for e in edges:
        if e["target"] in incoming and e["source"] in by_id:
            incoming[e["target"]] += 1

    def layer_rank(n: dict) -> int:
        t = n.get("type", "")
        if t == "domain":
            return 0
        if t in ("concept", "entity"):
            return 1 if incoming.get(n["id"], 0) == 0 else 2
        if t in ("synthesis", "comparison"):
            return 3
        if t in ("stance", "question"):
            return 4
        return 2

    sorted_nodes = sorted(skeleton_nodes, key=lambda n: (layer_rank(n), -n.get("degree", 0)))
    path = []
    for n in sorted_nodes:
        t = n.get("type", "")
        label = n.get("label", n["id"])
        if t == "domain":
            reason = "基础主题域"
        elif t in ("concept", "entity") and incoming.get(n["id"], 0) == 0:
            reason = "基础概念"
        elif t in ("concept", "entity"):
            reason = "进阶概念"
        elif t in ("synthesis", "comparison"):
            reason = "综合分析"
        elif t == "stance":
            reason = "立场判断"
        elif t == "question":
            reason = "开放问题"
        else:
            reason = ""
        path.append({"id": n["id"], "label": label, "reason": reason})
    return path


def _pick_start_node(nodes: list, edges: list) -> str:
    """Pick a good entry node for learning mode.

    Prefer a domain or concept with moderate degree (top quartile but not
    the single highest hub), in the largest community.
    """
    if not nodes:
        return ""
    community_sizes: dict[str, int] = {}
    for n in nodes:
        c = n.get("community", "")
        community_sizes[c] = community_sizes.get(c, 0) + 1
    largest_community = max(community_sizes, key=community_sizes.get) if community_sizes else ""

    candidates = [n for n in nodes
                  if n.get("type") in ("domain", "concept") and n.get("community") == largest_community]
    if not candidates:
        candidates = [n for n in nodes if n.get("type") in ("domain", "concept")]
    if not candidates:
        candidates = nodes

    degrees = sorted(n.get("degree", 0) for n in candidates)
    if len(degrees) >= 4:
        top_q = degrees[-(len(degrees) // 4)]
    else:
        top_q = degrees[-1] if degrees else 0
    low_q = degrees[len(degrees) // 4] if len(degrees) >= 4 else 0

    moderate = [n for n in candidates if low_q <= n.get("degree", 0) <= top_q]
    if not moderate:
        moderate = candidates
    return max(moderate, key=lambda n: n.get("degree", 0))["id"]


def adapt_graph_data_for_frontend(raw_data: dict, vault: Path) -> dict:
    """Adapt graph-data.json for the frontend, filling content from vault pages."""
    nodes_raw = raw_data.get("nodes", [])
    edges_raw = raw_data.get("edges", [])
    insights_raw = raw_data.get("insights", [])
    contradictions_raw = raw_data.get("contradictions", [])
    questions_raw = raw_data.get("questions", [])
    communities_raw = raw_data.get("communities", [])

    # Community labels
    community_labels: dict[int, str] = {}
    community_sizes: dict[int, int] = {}
    for c in communities_raw:
        cid = c.get("id", 0)
        community_labels[cid] = c.get("label", f"社区{cid}")
        community_sizes[cid] = c.get("size", 0)

    # Color palette (muted, unsaturated)
    palette = [
        "#7a96a6",  # dusty blue
        "#8a9c7a",  # sage
        "#c2a06a",  # ochre
        "#a78099",  # mauve
        "#b77a66",  # clay
        "#9a9666",  # olive
        "#7e8896",  # slate
        "#a38d6a",  # wheat
    ]

    # Map node types to display types and colors
    type_config = {
        "source":      {"label": "来源", "color": "#5a7a96"},
        "brief":       {"label": "简报", "color": "#8a8a6a"},
        "concept":     {"label": "概念", "color": "#5a8a6a"},
        "entity":      {"label": "实体", "color": "#8a6a8a"},
        "domain":      {"label": "域",   "color": "#8a7a5a"},
        "stance":      {"label": "立场", "color": "#7a5a5a"},
        "question":    {"label": "问题", "color": "#6a6a8a"},
        "synthesis":   {"label": "综合", "color": "#6a8a7a"},
        "comparison":  {"label": "对比", "color": "#8a8a6a"},
        "digest":      {"label": "Digest", "color": "#7a8a7a"},
    }

    # Adapt nodes with content and community info
    adapted_nodes = []
    for n in nodes_raw:
        node_type = n.get("type", "topic")
        cfg = type_config.get(node_type, {"label": node_type, "color": "#8a8a8a"})
        comm_id = n.get("community", 0)
        comm_color = palette[comm_id % len(palette)] if comm_id is not None else "#8a8a8a"

        # Read actual content from vault
        content = _read_node_content(vault, n["id"])

        adapted_nodes.append({
            "id": n["id"],
            "label": n.get("label", n["id"]),
            "type": node_type,
            "typeLabel": cfg["label"],
            "typeColor": cfg["color"],
            "community": community_labels.get(comm_id, f"社区{comm_id}"),
            "communityId": comm_id,
            "communityColor": comm_color,
            "content": content[:500],
            "source_path": n["id"],
            "date": n.get("date", ""),
            "degree": n.get("degree", 0),
        })

    # Adapt edges — keep original type names, add color/style info
    edge_styles = {
        "supports":    {"color": "#5a8a6a", "dash": False,  "width": 2},
        "contradicts": {"color": "#c05050", "dash": True,   "width": 2},
        "evolves":     {"color": "#5a7a96", "dash": False,  "width": 3},
        "answers":     {"color": "#6a6a8a", "dash": False,  "width": 1},
        "belongs_to":  {"color": "#8a8a8a", "dash": False,  "width": 1},
        "mentions":    {"color": "#aaaaaa", "dash": True,   "width": 1},
    }

    adapted_edges = []
    for i, e in enumerate(edges_raw):
        edge_type = e.get("type", "mentions")
        style = edge_styles.get(edge_type, edge_styles["mentions"])
        adapted_edges.append({
            "id": f"e{i}",
            "source": e["source"],
            "target": e["target"],
            "type": edge_type,
            "color": style["color"],
            "dash": style["dash"],
            "width": style["width"],
        })

    # Adapt contradictions for dedicated tracking
    adapted_contradictions = []
    for c in contradictions_raw:
        adapted_contradictions.append({
            "source": c["source"],
            "target": c["target"],
            "type": "contradicts",
        })

    # Adapt questions for tracking
    adapted_questions = []
    for q in questions_raw:
        adapted_questions.append({
            "id": q["id"],
            "title": q.get("title", ""),
            "status": q.get("status", "open"),
            "questionText": q.get("question_text", "")[:200],
        })

    # Adapt insights
    adapted_insights = {
        "bridgeNodes": [],
        "isolatedNodes": [],
        "contradictions": [],
        "summary": [],
    }
    for ins in insights_raw:
        ins_type = ins.get("type", "")
        if ins_type == "bridge_node":
            nodes_list = ins.get("nodes", [])
            if nodes_list:
                adapted_insights["bridgeNodes"].append({
                    "id": nodes_list[0],
                    "communityCount": len(ins.get("bridge_communities", [])),
                })
        elif ins_type == "isolated_node":
            nodes_list = ins.get("nodes", [])
            if nodes_list:
                adapted_insights["isolatedNodes"].append({
                    "id": nodes_list[0],
                })
        elif ins_type in ("cross_community_contradiction", "contradiction_summary"):
            adapted_insights["contradictions"].append({
                "description": ins.get("description", ""),
                "nodes": ins.get("nodes", []),
            })
        adapted_insights["summary"].append(ins.get("description", ""))

    # Classify nodes: skeleton (concepts/entities/domains/syntheses/comparisons)
    # vs detail (sources/briefs) for mode-specific visual treatment
    SKELETON_TYPES = {"concept", "entity", "domain", "synthesis", "comparison"}
    for n in adapted_nodes:
        n["nodeClass"] = "skeleton" if n["type"] in SKELETON_TYPES else "detail"

    # Build learning path: order skeleton nodes by dependency
    # Heuristic: domains first, then concepts/entities with fewest deps,
    # then syntheses/comparisons that depend on them, then stances/questions
    skeleton_nodes = [n for n in adapted_nodes if n["nodeClass"] == "skeleton"]
    path_order = _compute_learning_path(skeleton_nodes, adapted_edges)

    # Pick a better start node: prefer a domain or concept with moderate degree
    # (not the highest-degree hub which is usually a cross-cutting synthesis)
    start_node = _pick_start_node(adapted_nodes, adapted_edges)

    # Primary community
    primary_comm = community_labels.get(0, "") if community_labels else ""

    adapted_data = {
        "meta": {
            "build_date": date.today().isoformat(),
            "wiki_title": "Knowledge Base",
            "total_nodes": len(adapted_nodes),
            "total_edges": len(adapted_edges),
            "total_contradictions": len(adapted_contradictions),
            "total_questions": len(adapted_questions),
            "initial_view": [start_node],
        },
        "nodes": adapted_nodes,
        "edges": adapted_edges,
        "communities": [
            {
                "id": c.get("id", 0),
                "label": c.get("label", f"社区{c.get('id', 0)}"),
                "size": c.get("size", 0),
                "color": palette[c.get("id", 0) % len(palette)],
            }
            for c in communities_raw
        ],
        "contradictions": adapted_contradictions,
        "questions": adapted_questions,
        "insights": adapted_insights,
        "learning": {
            "version": 3,
            "entry": {
                "recommended_start_node_id": start_node,
                "default_mode": "global",
            },
            "path": path_order,
        },
    }
    return adapted_data


def build_graph_html(vault: Path) -> str:
    """Assemble the full interactive HTML page."""
    script_root = Path(__file__).resolve().parents[2]
    template_dir = script_root / "templates" / "graph-styles" / "wash"

    # Read templates
    header_path = template_dir / "header.html"
    footer_path = template_dir / "footer.html"
    if not header_path.exists() or not footer_path.exists():
        raise FileNotFoundError(f"Missing wash templates at {template_dir}")

    header = header_path.read_text(encoding="utf-8")
    footer = footer_path.read_text(encoding="utf-8")

    # Generate graph data with vault content
    raw_data = build_graph_data(vault)
    adapted = adapt_graph_data_for_frontend(raw_data, vault)
    graph_json = json.dumps(adapted, ensure_ascii=False, indent=2)

    # Replace placeholders in header
    header = header.replace("__WIKI_TITLE__", "Knowledge Base")
    header = header.replace("__NODE_COUNT__", str(adapted["meta"]["total_nodes"]))
    header = header.replace("__EDGE_COUNT__", str(adapted["meta"]["total_edges"]))
    header = header.replace("__BUILD_DATE__", adapted["meta"]["build_date"])

    # Embed graph data inline
    escaped_json = graph_json.replace("</script>", "<\\/script>")

    # Build full HTML
    parts = [header, escaped_json, "\n", footer]
    return "".join(parts)


def write_graph_html(vault: Path) -> Path:
    """Write wiki/knowledge-graph.html and copy vendor assets. Return the HTML path."""
    html_path = vault / "wiki" / "knowledge-graph.html"
    html_path.parent.mkdir(parents=True, exist_ok=True)

    html_content = build_graph_html(vault)
    html_path.write_text(html_content, encoding="utf-8")

    # Copy only d3.min.js (rough/marked/purify removed)
    script_root = Path(__file__).resolve().parents[2]
    deps_dir = script_root / "deps"
    target_dir = html_path.parent
    d3_src = deps_dir / "d3.min.js"
    if d3_src.exists():
        dst = target_dir / "d3.min.js"
        dst.write_bytes(d3_src.read_bytes())

    # Copy wash JS helpers
    wash_dir = script_root / "templates" / "graph-styles" / "wash"
    for js_file in ("graph-wash.js", "graph-wash-helpers.js"):
        src = wash_dir / js_file
        if src.exists():
            dst = target_dir / js_file
            dst.write_bytes(src.read_bytes())

    return html_path