"""Backward-compatibility shim — all functions re-exported from split modules.

The original shared.py has been split into:
  pipeline/pipeline_types.py — Article dataclass, WIKI_DIRS, constants
  pipeline/text_utils.py — regex helpers, plain_text, parse_frontmatter, section_excerpt
  pipeline/extractors.py — detect_domains, extract_concepts/entities, taxonomy helpers
  pipeline/vault_config.py — resolve_vault, vault registry, DEFAULT_DOMAINS, domain keywords

This shim preserves all existing import paths (from pipeline.shared import ...).
"""

from .pipeline_types import (
    Article,
    WIKI_DIRS,
    DOMAIN_MIN_SCORE,
    CONCEPT_PAGE_THRESHOLD,
    ENTITY_PAGE_THRESHOLD,
    VALID_PAGE_STATUS,
    STATUS_UPGRADE_THRESHOLDS,
    DOMAIN_EXCLUDE_LINES,
    GENERIC_ENTITY_STOPWORDS,
    ENGLISH_ENTITY_STOPWORDS,
    CONCEPT_STOPWORDS,
)
from .text_utils import (
    INVALID_CHARS,
    FRONTMATTER,
    IMAGE,
    LINK,
    CODE_BLOCK,
    HEADING,
    SECTION_PATTERN,
    CLAIM_PATTERN,
    sanitize_filename,
    slugify_article,
    parse_frontmatter,
    plain_text,
    split_sentences,
    normalize_sentence,
    top_lines,
    brief_lead,
    section_excerpt,
    section_body,
    get_one_sentence,
    filename_stem,
    body_text,
    body_lines,
    validate_apply_json,
)
from .extractors import (
    concept_slug,
    entity_slug,
    domain_slug,
    comparison_slug,
    page_mention_count,
    mature_concepts,
    mature_entities,
    existing_taxonomy_links,
    vault_domain_distribution,
    detect_domain_mismatch,
)
from .vault_config import (
    CONF_DIR,
    VAULTS_JSON,
    VAULT_CONF,
    DEFAULT_DOMAINS,
    video_id_from_url,
    normalize_collection_url,
    transcript_fidelity,
    transcript_page_name,
    transcript_page_link,
    load_vault_registry,
    save_vault_registry,
    parse_purpose_md,
    load_domain_keywords,
    select_vault_by_domains,
    resolve_vault,
    _discover_obsidian_vault,
)

__all__ = [
    "Article",
    "WIKI_DIRS",
    "DEFAULT_DOMAINS",
    "DOMAIN_MIN_SCORE",
    "CONCEPT_PAGE_THRESHOLD",
    "ENTITY_PAGE_THRESHOLD",
    "VALID_PAGE_STATUS",
    "STATUS_UPGRADE_THRESHOLDS",
    "DOMAIN_EXCLUDE_LINES",
    "GENERIC_ENTITY_STOPWORDS",
    "ENGLISH_ENTITY_STOPWORDS",
    "CONCEPT_STOPWORDS",
    "INVALID_CHARS",
    "FRONTMATTER",
    "IMAGE",
    "LINK",
    "CODE_BLOCK",
    "HEADING",
    "SECTION_PATTERN",
    "CLAIM_PATTERN",
    "sanitize_filename",
    "slugify_article",
    "parse_frontmatter",
    "plain_text",
    "split_sentences",
    "normalize_sentence",
    "top_lines",
    "brief_lead",
    "section_excerpt",
    "section_body",
    "filename_stem",
    "body_text",
    "body_lines",
    "validate_apply_json",
    "concept_slug",
    "entity_slug",
    "domain_slug",
    "comparison_slug",
    "page_mention_count",
    "mature_concepts",
    "mature_entities",
    "existing_taxonomy_links",
    "vault_domain_distribution",
    "detect_domain_mismatch",
    "CONF_DIR",
    "VAULTS_JSON",
    "VAULT_CONF",
    "video_id_from_url",
    "normalize_collection_url",
    "transcript_fidelity",
    "transcript_page_name",
    "transcript_page_link",
    "load_vault_registry",
    "save_vault_registry",
    "parse_purpose_md",
    "load_domain_keywords",
    "select_vault_by_domains",
    "resolve_vault",
    "_discover_obsidian_vault",
]