from __future__ import annotations

import os


ENV_MAP: dict[str, str] = {
    "KWIKI_WEB_ADAPTER_BIN": "WECHAT_WIKI_WEB_ADAPTER_BIN",
    "KWIKI_VIDEO_ADAPTER_BIN": "WECHAT_WIKI_VIDEO_ADAPTER_BIN",
    "KWIKI_VIDEO_COOKIES_FILE": "WECHAT_WIKI_VIDEO_COOKIES_FILE",
    "KWIKI_VIDEO_COOKIES_FROM_BROWSER": "WECHAT_WIKI_VIDEO_COOKIES_FROM_BROWSER",
    "KWIKI_ASR_MODEL": "WECHAT_WIKI_ASR_MODEL",
    "KWIKI_ASR_COMPUTE_TYPE": "WECHAT_WIKI_ASR_COMPUTE_TYPE",
    "KWIKI_NODE_BIN": "WECHAT_WIKI_NODE_BIN",
    "KWIKI_DOUYIN_USER_AGENT": "WECHAT_WIKI_DOUYIN_USER_AGENT",
    "KWIKI_DOUYIN_HEADLESS": "WECHAT_WIKI_DOUYIN_HEADLESS",
    "KWIKI_COMPILE_MOCK_FILE": "WECHAT_WIKI_COMPILE_MOCK_FILE",
    "KWIKI_API_KEY": "WECHAT_WIKI_API_KEY",
    "KWIKI_COMPILE_MODEL": "WECHAT_WIKI_COMPILE_MODEL",
    "KWIKI_API_BASE": "WECHAT_WIKI_API_BASE",
    "KWIKI_COMPILE_TEMPERATURE": "WECHAT_WIKI_COMPILE_TEMPERATURE",
    "KWIKI_COMPILE_MAX_TOKENS": "WECHAT_WIKI_COMPILE_MAX_TOKENS",
    "KWIKI_WECHAT_TOOL_DIR": "WECHAT_ARTICLE_FOR_AI_DIR",
    "KWIKI_DEPS_DIR": "WECHAT_ARTICLE_PYTHONPATH",
}


def resolve_env(new_key: str, default: str = "") -> str:
    value = os.environ.get(new_key, "").strip()
    if value:
        return value
    old_key = ENV_MAP.get(new_key, "")
    if old_key:
        return os.environ.get(old_key, default).strip()
    return default
